version: "3.8"

services:
  productDb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=productDb
    ports:
      - "4000:3306"
    volumes:
      - productDb:/var/lib/mysql
    networks:
      - uit

  # orderDb:
  #   image: mysql:latest
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=1234
  #     - MYSQL_DATABASE=orderDb
  #   ports:
  #     - "4001:3306"
  #   volumes:
  #     - orderDb:/var/lib/mysql

  # customerDb:
  #   image: mysql:latest
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=1234
  #     - MYSQL_DATABASE=customerDb
  #   ports:
  #     - "4002:3306"
  #   volumes:
  #     - customerDb:/var/lib/mysql
      
  cartDb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=cartDb
    ports:
      - "4003:3306"
    volumes:
      - cartDb:/var/lib/mysql
    networks:
      - uit

  configserver:
    image: tonyyou998/ecommerce_config_server:1.0.0
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - uit

  eurekaserver:
   image: tonyyou998/ecommerce_eureka_server:1.0.0
   ports:
     - "8761:8761"
   networks:
   - uit
   depends_on:
     - configserver
   deploy:
     restart_policy:
       condition: on-failure
       delay: 10s
       max_attempts: 3
       window: 120s
   environment:
     SPRING_PROFILES_ACTIVE: dev
     SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/


  gatewayserver:
   image: tonyyou998/ecommerce_gateway_server:1.1.0
   ports:
     - "8080:8080"
   networks:
   - uit
   depends_on:
     - configserver
     - eurekaserver
   deploy:
     restart_policy:
       condition: on-failure
       delay: 40s
       max_attempts: 3
       window: 120s
   environment:
    SPRING_PROFILES_ACTIVE: prod
    SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "7080:8080" 
    networks:
    - uit
    deploy:
      restart_policy:
        condition: on-failure
        delay: 120s
        max_attempts: 3
        window: 120s
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: "start-dev"
    
   
  product_service:
   image: tonyyou998/ecommerce_product_service:1.3.0
   ports:
     - "8084:8084"
   networks:
   - uit
   depends_on:
     - configserver
     - eurekaserver
     - gatewayserver
     - productDb
   deploy:
     restart_policy:
       condition: on-failure
       delay: 120s
       max_attempts: 3
       window: 120s
   environment:
    SPRING_PROFILES_ACTIVE: prod
    SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    SPRING_DATASOURCE_URL: jdbc:mysql://productDb:3306/productDb
  
  cart_service:
   image: tonyyou998/ecommerce_cart_service:1.1.0
   ports:
     - "8081:8081"
   networks:
   - uit
   depends_on:
     - configserver
     - eurekaserver
     - gatewayserver
     - cartDb
   deploy:
     restart_policy:
      condition: on-failure
      delay: 120s
      max_attempts: 3
      window: 120s
   environment:
    SPRING_PROFILES_ACTIVE: prod
    SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    SPRING_DATASOURCE_URL: jdbc:mysql://cartDb:3306/cartDb




volumes:
  productDb:
  cartDb:
  # orderDb:
  # customerDb:
  
networks:
  uit:
    driver: bridge