version: "3.8"

services:
  productDb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=productDb
    ports:
      - "4000:3306"
    networks:
      - uit
    volumes:
      - productDb:/var/lib/mysql

  # orderDb:
  #   image: mysql:5.7
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=1234
  #     - MYSQL_DATABASE=orderDb
  #   ports:
  #     - "4001:3306"
  #   networks:
  #     - uit
  #   volumes:
  #     - orderDb:/var/lib/mysql
  # customerDb:
  #   image: mysql:5.7
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=1234
  #     - MYSQL_DATABASE=customerDb
  #   ports:
  #     - "4002:3306"
  #   networks:
  #     - uit
  #   volumes:
  #     - customerDb:/var/lib/mysql
      
  # cartDb:
  #   image: mysql:5.7
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=1234
  #     - MYSQL_DATABASE=cartDb
  #   ports:
  #     - "4003:3306"
  #   networks:
  #     - uit
  #   volumes:
  #     - cartDb:/var/lib/mysql

  configserver:
    image: tonyyou998/ecommerce_config_server:1.0.0
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - uit

  eurekaserver:
   image: tonyyou998/ecommerce_eureka_server:1.0.0
   ports:
     - "8761:8761"
   networks:
   - uit
   depends_on:
     - configserver
   deploy:
     restart_policy:
       condition: on-failure
       delay: 10s
       max_attempts: 3
       window: 120s
   environment:
     SPRING_PROFILES_ACTIVE: dev
     SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/


  gatewayserver:
   image: tonyyou998/ecommerce_gateway_server:1.0.2
   ports:
     - "8080:8080"
   networks:
   - uit
   depends_on:
     - configserver
     - eurekaserver
   deploy:
     restart_policy:
       condition: on-failure
       delay: 40s
       max_attempts: 3
       window: 120s
   environment:
    SPRING_PROFILES_ACTIVE: prod
    SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
 
  product_service:
   image: tonyyou998/ecommerce_product_service:1.1.1
   ports:
     - "8084:8084"
   networks:
   - uit
   depends_on:
     - configserver
     - eurekaserver
     - gatewayserver
   deploy:
     restart_policy:
       condition: on-failure
       delay: 60s
       max_attempts: 3
       window: 120s
   environment:
    SPRING_PROFILES_ACTIVE: prod
    SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    # SPRING_DATASOURCE_URL: jdbc:mysql://productDb:3306/productDb


  # orderDb:
  #   image: mysql:5.7
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=1234
  #     - MYSQL_DATABASE=orderDb
  #   ports:
  #     - "4001:3306"
  #   networks:
  #     - uit
  #   volumes:
  #     - orderDb:/var/lib/mysql

volumes:
  productDb:
  orderDb:
  customerDb:
  cartDb:


networks:
  uit: