
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: 'http://localhost:8761/eureka/'
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"
  profiles:
    active: 'dev'
  cloud:
    gateway:
      default-filters:
       - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:3000"
            allowed-methods: "*"
            allowed-headers: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  application:
    name: 'gatewayserver'
  config:
    import: 'optional:configserver:http://localhost:8071/'
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: 'gatewayserver'
    description: 'Gateway Server Application'
    version: '1.0.0'
logging:
  level:
    com:
      uit:
        gatewayserver: DEBUG
